### ISSUE TITLE
Update old dependencies

### ISSUE THREAD

**Issue by dpogue** [dumbmatter/fakeIndexedDB#10]
Some of the shrinkwrapped dependencies are quite old and are causing deprecation warnings when installing. In particular, `graceful-fs` and `minimatch`, which are dependencies of `mocha`.

I've verified that all tests pass if mocha is upgraded to the latest release (mocha@3.0.2).

**Comment by dumbmatter** [comment]
Good point, I upgraded all the dependencies that didn't have breaking changes.

v1.0.8 has the changes.

**Comment by dpogue** [comment]
🙌 You're awesome! Thanks
