### ISSUE TITLE
Use FIDB within web workers 

### ISSUE THREAD

**Issue by tresdin** [dumbmatter/fakeIndexedDB#11]
I think FIDB should use `self` as the global object instead of `window`. Otherwise, it won't work within web worker contexts.

**Comment by dumbmatter** [comment]
Sounds reasonable, assuming it doesn't cause any problems elsewhere. I'd accept a PR, or if you wait a bit I would probably get around to it myself eventually :)

**Comment by tresdin** [comment]
@dumbmatter You can feel free to fix it yourself as soon as possible.

**Comment by dumbmatter** [comment]
Closed with https://github.com/dumbmatter/fakeIndexedDB/commit/1c9ef84af54937f5062885e074b59272463f0a58 which references the wrong issue number in the commit :)
