### ISSUE TITLE
Question: Is there an easy way to reset all data in the RAM database?

### ISSUE THREAD

**Issue by jcalfee** [dumbmatter/fakeIndexedDB#2]
I'm using fakeIndexedDB in my unit tests.  It would be great to make one method call and delete all object stores.  This would be used after each test.

**Comment by dumbmatter** [comment]
You want it to delete all object stores, or delete all data within all object stores while leaving the stores there? Because if it's the former, you could just use `fakeIndexedDB.deleteDatabase` since a database with no object stores isn't doing you much good.

**Comment by jcalfee** [comment]
A clean slate.  The idea is that each unit test should re-build everything it needs and should not be influenced or depend on another test.  That keeps is simple.

Thanks for the help.  I have other requests like this they seem to work.  Is it possible that the call back for `deleteDatabase` is not implemented? Below the  done() is not being called and there is no error.

```
before( done => {
        var request = fakeIndexedDB.deleteDatabase("graphene_db")
        request.onsuccess = ()=>{ done() }
        request.onerror = e => {console.error(e)}
 })
```

**Comment by jcalfee** [comment]
I see you seem to be very well tested in this area in your own unit tests (via the version 1.0.3 tag) ....  It must be something in my code.  I'll let you know if I come up with something useful.  Thanks again.

**Comment by dumbmatter** [comment]
Make sure you call db.close first, I might not be handling deleting an open
database correctly. Need to investigate more.

**Comment by dumbmatter** [comment]
Yeah, there is definitely a problem with deleting databases that still have open connections. This hangs:

    var fakeIndexedDB = require('fake-indexeddb');
    fakeIndexedDB.open('test', 1);
    fakeIndexedDB.deleteDatabase('test');

The same problem occurs when running a versionchange transaction on databases that still have open connections:

    var fakeIndexedDB = require('fake-indexeddb');
    fakeIndexedDB.open('test', 1);
    fakeIndexedDB.open('test', 2);

In [both](http://www.w3.org/TR/IndexedDB/#dfn-steps-for-deleting-a-database) [cases](http://www.w3.org/TR/IndexedDB/#dfn-steps-for-running-a-versionchange-transaction), the spec says something like:

> Fire a `versionchange` event at each open database. Then fire a `blocked` event at each database that is still open. Then wait for all databases to be closed before proceeding.

But... I don't understand what is actually supposed to be closing the databases. Nothing in fakeIndexedDB does it, so it gets stuck waiting for all databases to close before proceeding.

Probably it is described in the spec somewhere and I am just missing it.

**Comment by spralle** [comment]
I had a problem getting proper deleteDatabase to work (data seemed to be there when I opened again) and no time to figure out why so I did something ugly but worked for me `idb._databases.clear();`

**Comment by MoeSauber** [comment]
```
fakeIndexedDB.deleteDatabase('test');
```
It works fine if the DB does not exist (calling `onsuccess`), but if the DB actually exists, it seems to be stuck for me. Neither `onerror` nor `onsuccess` ever get called.
