### ISSUE TITLE
Be more picky about core-js include

### ISSUE THREAD

**Issue by MarkKahn** [dumbmatter/fakeIndexedDB#25]
The blanket include of core-js is causing some issues in our project.  Specifically there is a package in core-js that introduces numbers as iterators (e.g. you can write `for (i of 20) {`).  React tends to blow up with this, and if you return a number from a render function you get long strings of zeros for some reason.  So some of our tests now look like `Expected 10, got "000000000000000000000000000000000000000000000000000000000000000"`

Suggest that the project be updated to include specific polyfills that are needed as opposed to a blanket include, or at least only enabling stage 2 features

**Comment by dumbmatter** [comment]
Wow, that's crazy! I'd be happy to accept a PR. I'm not sure what exactly I'd need to retain to support Node 4 and PhantomJS, and I'm not sure of the best way to include only those features.

**Comment by dumbmatter** [comment]
Also, you might want to submit a bug report to core-js too, if that is the real source of this problem.

**Comment by zloirock** [comment]
@dumbmatter it's not a bug, it's a legacy non-standard feature. It's removed from `core-js@3`. If you use `core-js@2` and it causes problems for you, use only stable `core-js` features.

**Comment by dumbmatter** [comment]
Interesting, thanks for the info! I'll give it a shot.

**Comment by dumbmatter** [comment]
I published v2.0.5, hopefully that solves this issue.
