### ISSUE TITLE
Property's name Event.timestamp is wrong

### ISSUE THREAD

**Issue by duduindo** [dumbmatter/fakeIndexedDB#30]
### Code line
https://github.com/dumbmatter/fakeIndexedDB/blob/master/src/lib/FakeEvent.ts#L28

### MDN
https://developer.mozilla.org/en-US/docs/Web/API/Event/timeStamp

### Diff
```js
// Wrong
public timestamp = Date.now();
```
```js
// Right
public timeStamp = Date.now();
```

### Thankfulness
This mock is awesome! Thanks

**Comment by dumbmatter** [comment]
Fixed in v2.1.1. Thanks for noticing this!
