### ISSUE TITLE
objectStoreNames.contains

### ISSUE THREAD

**Issue by ForNeVeR** [dumbmatter/fakeIndexedDB#4]
According to the [spec](http://www.w3.org/TR/2015/REC-IndexedDB-20150108/#database-interface), `db.objectStorenames` should have the [`DOMStringList` type](https://developer.mozilla.org/en-US/docs/Web/API/DOMStringList) that resembles `Array` but have the `contains` method. Currently your implementation lacks of this method.

**Comment by dumbmatter** [comment]
You're right. I did try to account for that, but never came up with a good solution. Subclassing `Array` seems fraught with peril, or maybe I just don't know enough. PRs and/or ideas are welcome :)

Side note: it is complete and utter madness that `DOMStringList.contains` exists but `Array.contains` doesn't!

**Comment by dumbmatter** [comment]
Fixed in version 1.0.6
