### ISSUE TITLE
Feature Request: Ability to totally wipe/reset state

### ISSUE THREAD

**Issue by adueck** [dumbmatter/fakeIndexedDB#40]
I would love to have an option to be able to delete all databases and totally reset the state of the indexedDB mock. 

My use case:
- Testing some functions using an external library that works with indexedDB
- That library **doesn't tell me the names of the databases that it's creating** / working with
- After each test, I want to be able to **totally reset the state of indexedDB**, regardless of what databases may or may not have been created 

Because of this situation, I'm note able to make the solution found by @jcalfee [here](https://github.com/dumbmatter/fakeIndexedDB/issues/2#issuecomment-119570488).

```
fakeIndexedDB.deleteDatabase("unknown name") // can't because I don't know the name
```

And there [doesn't seem to be a standard way](https://stackoverflow.com/questions/46040005/delete-all-indexeddb) to do a wipe of all dbs in indexedDB.

So for the sake of testing (especially if testing stuff using 3rd party libraries that interact with `indexedDB`), it would be great if a special method could be added to totally wipe and reset the state of `indexedDB`.

**Comment by dumbmatter** [comment]
A couple things you could do...

1. Create a new fakeIndexedDB instance when you want to start from scratch:

       const FDBFactory = require("fake-indexeddb/lib/FDBFactory");
       const fakeIndexedDB = new FDBFactory();

2. Peek into the internals of fakeIndexedDB to see the names of all current databases:

       const databaseNames = Array.from(fakeIndexedDB._databases.keys());

I should probably document this in the README.

**Comment by adueck** [comment]
Thanks so much. I wasn't able to get number 2 working in my case (I could get the DB names but for some reason I wasn't able to delete them 🤷‍♂️), but **1. worked great** when I did this: (I'm using Jest)

```js
require("fake-indexeddb/auto");
const FDBFactory = require("fake-indexeddb/lib/FDBFactory");

afterEach(() => {
  indexedDB = new FDBFactory();
});
```

Now I have totally isolated tests with a fresh `indexedDB` each time! 😄
