### ISSUE TITLE
Transactions/Cursors fail with `jsdom`

### ISSUE THREAD

**Issue by ph-fritsche** [dumbmatter/fakeIndexedDB#67]
With `jsdom` environment in `jest@27` acting on a transaction after allowing other code to run (per `await`) throws errors.
This differs from executing the same calls in a `node` environment.

Maybe this is related to #64 

https://github.com/ph-fritsche/repro-jest-jsdom-indexeddb

**Comment by dumbmatter** [comment]
Thanks for the repo with a reproduction!

It does seem like it could be related to #64... but if I put `jest.useRealTimers();` at the top of your test script, it still fails. So maybe it's something else jsdom is doing, not the timers? I dunno. I've never really used it before.

Anyone have any ideas? If it was as simple as using real timers, I could do it like suggested in #64 probably, but it doesn't seem to be that simple...

**Comment by ath0mas** [comment]
After update from v3.1.3 to v3.1.4 that contains only this fix, my Mocha tests started failing 😢 I'll try to create a reproduction repo before opening corresponding issue

**Comment by ph-fritsche** [comment]
@ath0mas Do you have fake timers in place that might need to be advanced so that the calls to `setTimeout` in https://github.com/dumbmatter/fakeIndexedDB/commit/17c15473e0dd61a32240431573d21a1b4f5b150e are resolved?
