### ISSUE TITLE
initialize the DB before the use.

### ISSUE THREAD

**Issue by alirezahmz** [dumbmatter/fakeIndexedDB#73]
I use the react testing library to test and I get an error when I run the test.
how to initialize indexDB in react testing library?
![indexDB](https://user-images.githubusercontent.com/64639961/145045227-39d7ed3b-6e05-4544-87db-b1379d6ebabf.PNG)

**Comment by dumbmatter** [comment]
I've never used React Testing Library, but I think people usually use it with Jest, right? If you're using Jest, there are instructions in the README.

If that doesn't work, please provide more information, such as some minimal code I can run to observe the error.

**Comment by alirezahmz** [comment]
this issue was solved, cause I didn't call indexDB provider correctly in my test wrapper.
