### ISSUE TITLE
Release new version to npm with latest types fix

### ISSUE THREAD

**Issue by sceee** [dumbmatter/fakeIndexedDB#84]
Hi,

Would it be possible to release a new version to npm with the latest type fix from https://github.com/dumbmatter/fakeIndexedDB/commit/b63520cd7e23c22e6488424aa9b2c6714c320456 ?

The current release on npm (v4.0.1) does not yet contain this fix and creates typescript compile errors on some projects.

**Comment by dumbmatter** [comment]
Sure, I didn't know it was actually affecting anyone. Will release a new version shortly.

**Comment by sceee** [comment]
@dumbmatter thanks for the fast response!

**Comment by dumbmatter** [comment]
You caught me at a good time :)
