### ISSUE TITLE
DataCloneError: The data being stored could not be cloned by the internal structured cloning algorithm.

### ISSUE THREAD

**Issue by rwxmad** [dumbmatter/fakeIndexedDB#85]
I created a test where I check if the Blob object was added to indexeddb , but when I run the test, it fails 
Test:
```ts
import "fake-indexeddb/auto";
import { IndexDBKeyValueBlobStorage } from "./IndexDBKeyValueBlobStorage";

const DB_NAME = "db";
const DB_VERSION = 3;
const STORE_NAME = "test";
const INDEX = "index";

describe("setAsync", () => {
  test("should find record", async () => {
    const db = new IndexDBKeyValueBlobStorage(DB_NAME, DB_VERSION);
    const value = new Blob(
      [JSON.stringify({ name: "test", age: 25 }, null, 2)],
      {
        type: "application/json",
      }
    );

    const result = await db.setAsync(STORE_NAME, INDEX, value);
  });
});
```
Error:
![Screenshot 2023-08-15 at 14 41 03](https://github.com/dumbmatter/fakeIndexedDB/assets/30772868/e596f69c-6367-4e98-ad77-4b10a24a7737)

**Comment by dumbmatter** [comment]
What version of Node.js are you using? Blobs should work, but maybe only in Node 18 or newer https://github.com/dumbmatter/fakeIndexedDB/issues/56#issuecomment-1236166287

If you're on Node 18+ and it's still not working, can you post a full code example I can run to see the problem myself?

**Comment by rwxmad** [comment]
> What version of Node.js are you using? Blobs should work, but maybe only in Node 18 or newer [#56 (comment)](https://github.com/dumbmatter/fakeIndexedDB/issues/56#issuecomment-1236166287)
> 
> If you're on Node 18+ and it's still not working, can you post a full code example I can run to see the problem myself?

Аfter updating nodejs the error is gone, thanks a lot
