### ISSUE TITLE
`Uint8Array` keys don't respect offsets from underlying ArrayBuffers

### ISSUE THREAD

**Issue by joeltg** [dumbmatter/fakeIndexedDB#89]
In `valueToKey`, when you convert from `Uint8Array` or other data view (tested by `ArrayBuffer.isView`), the code currently returns `new Uint8Array(input.buffer).buffer`. This disregards the `byteOffset` and `byteLength`, which might only reference a slice of the underlying ArrayBuffer.

**Comment by dumbmatter** [comment]
Thanks you're right, does PR #90 look like a good fix?

**Comment by joeltg** [comment]
Yeah that looks great!

**Comment by dumbmatter** [comment]
Fixed in v5.0.1
