### ISSUE TITLE
`IDBObjectStore.count` is `O(n^2)`

### ISSUE THREAD

**Issue by richvdh** [dumbmatter/fakeIndexedDB#94]
The implementation of `IDBObjectStore.count` uses a cursor internally, which would be fine, except that iterating a cursor is `O(n)` in the number of entries in the store (`FDBCursor.iterate` looks through all entries until it finds one whose position is greater than that of the cursor).

The net result is that `IDBObjectStore.count` is *extremely* slow, to the extent that it's much faster to call `IDBObjectStore.getAllKeys()` and count the results in the array... provided, of course, that it fits in memory.

**Comment by dumbmatter** [comment]
Yeah that is excessively slow! Well, a lot of things in this library are not exactly optimized for speed, but if it's a small amount of code for a big speed up, then that should be done.

Does #95 fix things for your use case?

**Comment by richvdh** [comment]
Wow, that was quick! Yes, that's much better, thank you!

**Comment by dumbmatter** [comment]
I saw the notification and was like "come on, no way it's that slow" so I had to investigate and... it was that slow lol

Released in version 5.0.2
