### ISSUE TITLE
How to read one of the chrome database

### ISSUE THREAD

**Issue by mortinlojen3030** [dumbmatter/fakeIndexedDB#97]
I'm trying to read the database like this, but nothing comes up. objectStoreNames empty. What am I doing wrong?

> import "fake-indexeddb/auto";
> 
> const dbPath = "C:\\Users\\admin\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\IndexedDB\\chrome-extension_extension_0.indexeddb.leveldb";
> 
> let request = indexedDB.open(dbPath);
> 
> request.onsuccess = (event) => {
>   console.log(event.target.result.objectStoreNames); // return []
> }

**Comment by dumbmatter** [comment]
That's not what this library is for. In theory someone could write something to read data from Chrome's IndexedDB, but that might be better left for a separate project.
